### ISSUE TITLE
Scantily Outfit on LoLa

### ISSUE THREAD

**Issue by thomas992** [MasterQ32/LoLa-native#44]
![Screenshot from 2022-08-15 12-18-16](https://user-images.githubusercontent.com/31554741/184673992-93c2d723-6555-42ca-89f0-8b916decfe1f.png)

when the web browser displays the icon it is half the size, a scanty blur. I am planning on using LoLa for a language learning website using zig-gamedev, marketing to English, Dutch and Spanish speakers who may want to learn Japanese. The image resembles a school girl outfit in a tight white shirt, not something I would want to direct foreigners too when they start Japanese language learning. The percentage of foreigners who quit learning Japanese before they can speak it is above the 90 something percent. An embedded scripting language for WASM is an integral part of rendering, the part that allows creativity, the part worth sharing. I think it is the best way to teach programming is through the web browser with an embedded scripting language in a game.

### Replacing seductive anime girls
![Screenshot from 2022-08-15 12-36-22](https://user-images.githubusercontent.com/31554741/184676877-990d456a-cb54-4706-9e68-36cc0e538f94.png)

I think correlating an embedding scripting language to an anime mascot is like turning the third dimension into a counter culture vending machine, which is introspective in itself.

**Comment by ikskuh** [comment]
The mascot, logo and language name are fixed and won't change in the future.
